### ISSUE TITLE
Whats the deal with all the white space and commented out code?

### ISSUE THREAD

**Issue by jojobyte** [bnnanet/landing-funnel#1]
https://github.com/bnnanet/landing-funnel/blob/d54217ad282faca95d2a12301e08d3185f452071/.jshintrc#L1-L6
https://github.com/bnnanet/landing-funnel/blob/d54217ad282faca95d2a12301e08d3185f452071/.jshintrc#L13-L14
https://github.com/bnnanet/landing-funnel/blob/d54217ad282faca95d2a12301e08d3185f452071/jsconfig.json#L3-L13
https://github.com/bnnanet/landing-funnel/blob/d54217ad282faca95d2a12301e08d3185f452071/jsconfig.json#L15-L25

At this point, why not just add one comment at the top like
```js
/* Visit https://aka.ms/tsconfig to read more about this file */
```

and point to the template so you reference there but keep this clean?

**Comment by coolaj86** [comment]
It's just generated code from tools: `tsc init`, etc.

The extra white space at the top is from auto converting a json5 template to json, but I can probably fix that for the future - just need to add any such files to the formatter path, or use some magic sed to trim leading white space.
